/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jooq.setup;

import org.jooq.DSLContext;
import org.jooq.Result;
import org.jooq.impl.DSL;

import jooq.setup.tables.records.CityRecord;

public class App {
    public String getGreeting() {
        DSLContext dslContext = DSL.using("jdbc:postgresql://localhost:5499/world-db", "world", "world123");
        Result<CityRecord> records = dslContext.selectFrom(Tables.CITY)
                .fetch();
        return records.get(0).toString();
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
