/*
 * This file is generated by jOOQ.
 */
package jooq.setup.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CountryLanguage implements Serializable {

    private static final long serialVersionUID = 1L;

    private final String countryCode;
    private final String language;
    private final Boolean isOfficial;
    private final Float percentage;

    public CountryLanguage(CountryLanguage value) {
        this.countryCode = value.countryCode;
        this.language = value.language;
        this.isOfficial = value.isOfficial;
        this.percentage = value.percentage;
    }

    public CountryLanguage(
        String countryCode,
        String language,
        Boolean isOfficial,
        Float percentage
    ) {
        this.countryCode = countryCode;
        this.language = language;
        this.isOfficial = isOfficial;
        this.percentage = percentage;
    }

    /**
     * Getter for <code>public.country_language.country_code</code>.
     */
    public String getCountryCode() {
        return this.countryCode;
    }

    /**
     * Getter for <code>public.country_language.language</code>.
     */
    public String getLanguage() {
        return this.language;
    }

    /**
     * Getter for <code>public.country_language.is_official</code>.
     */
    public Boolean getIsOfficial() {
        return this.isOfficial;
    }

    /**
     * Getter for <code>public.country_language.percentage</code>.
     */
    public Float getPercentage() {
        return this.percentage;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final CountryLanguage other = (CountryLanguage) obj;
        if (this.countryCode == null) {
            if (other.countryCode != null)
                return false;
        }
        else if (!this.countryCode.equals(other.countryCode))
            return false;
        if (this.language == null) {
            if (other.language != null)
                return false;
        }
        else if (!this.language.equals(other.language))
            return false;
        if (this.isOfficial == null) {
            if (other.isOfficial != null)
                return false;
        }
        else if (!this.isOfficial.equals(other.isOfficial))
            return false;
        if (this.percentage == null) {
            if (other.percentage != null)
                return false;
        }
        else if (!this.percentage.equals(other.percentage))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.countryCode == null) ? 0 : this.countryCode.hashCode());
        result = prime * result + ((this.language == null) ? 0 : this.language.hashCode());
        result = prime * result + ((this.isOfficial == null) ? 0 : this.isOfficial.hashCode());
        result = prime * result + ((this.percentage == null) ? 0 : this.percentage.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("CountryLanguage (");

        sb.append(countryCode);
        sb.append(", ").append(language);
        sb.append(", ").append(isOfficial);
        sb.append(", ").append(percentage);

        sb.append(")");
        return sb.toString();
    }
}
