/*
 * This file is generated by jOOQ.
 */
package jooq.setup;


import java.util.Arrays;
import java.util.List;

import jooq.setup.tables.City;
import jooq.setup.tables.Country;
import jooq.setup.tables.CountryFlag;
import jooq.setup.tables.CountryLanguage;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.city</code>.
     */
    public final City CITY = City.CITY;

    /**
     * The table <code>public.country</code>.
     */
    public final Country COUNTRY = Country.COUNTRY;

    /**
     * The table <code>public.country_flag</code>.
     */
    public final CountryFlag COUNTRY_FLAG = CountryFlag.COUNTRY_FLAG;

    /**
     * The table <code>public.country_language</code>.
     */
    public final CountryLanguage COUNTRY_LANGUAGE = CountryLanguage.COUNTRY_LANGUAGE;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            City.CITY,
            Country.COUNTRY,
            CountryFlag.COUNTRY_FLAG,
            CountryLanguage.COUNTRY_LANGUAGE
        );
    }
}
