/*
 * This file is generated by jOOQ.
 */
package jooq.setup;


import jooq.setup.tables.City;
import jooq.setup.tables.Country;
import jooq.setup.tables.CountryFlag;
import jooq.setup.tables.CountryLanguage;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.city</code>.
     */
    public static final City CITY = City.CITY;

    /**
     * The table <code>public.country</code>.
     */
    public static final Country COUNTRY = Country.COUNTRY;

    /**
     * The table <code>public.country_flag</code>.
     */
    public static final CountryFlag COUNTRY_FLAG = CountryFlag.COUNTRY_FLAG;

    /**
     * The table <code>public.country_language</code>.
     */
    public static final CountryLanguage COUNTRY_LANGUAGE = CountryLanguage.COUNTRY_LANGUAGE;
}
